apiVersion: v1
kind: ConfigMap
metadata:
  name: html-data-configmap
data:
  index.html: This is index.html stored in Kubernetes ConfigMap!
  phpinfo.php: |
    <?php
    phpinfo();
  training: Kubernetes
  company: NobleProg
  trainer: Kamil Baran
