---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
spec:
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: kamilbaran/nobleprog_training:httpd
        volumeMounts:
        - name: html-data
          mountPath: /var/www/localhost/htdocs/
      volumes:
        - name: html-data
          configMap:
            name: html-data-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: training
spec:
  type: NodePort
  selector:
    app: training
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32081
