---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: training
spec:
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: kamilbaran/nobleprog_training:httpd
        env:
        - name: TRAINING
          valueFrom:
            secretKeyRef:
              name: html-data-secret
              key: training
        - name: COMPANY
          valueFrom:
            secretKeyRef:
              name: html-data-secret
              key: company

---
apiVersion: v1
kind: Service
metadata:
  name: training
spec:
  type: NodePort
  selector:
    app: training
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32080
