---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  labels:
    app: training
spec:
  selector:
    matchLabels:
      app: training
  replicas: 3
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: kamilbaran/nobleprog_training:training_app_v1
        resources:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-1
