apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: wordpress-training
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
