---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-mongo
  labels:
    app: counter
    component: database
    version: 1.0.0
spec:
  selector:
    matchLabels:
      app: counter
      component: database
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
        component: database
    spec:
      containers:
      - name: mongo
        image: kamilbaran/nobleprog_training:mongo
        ports:
        - containerPort: 27017
        command: ["/usr/bin/mongod", "--dbpath=/data/db", "--bind_ip_all"] 

---
apiVersion: v1
kind: Service
metadata:
  name: counter-mongo
  labels:
    app: counter
    component: database
spec:
  selector:
    app: counter
    component: database
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-httpd
  labels:
    app: counter
    component: frontend
spec:
  selector:
    matchLabels:
      app: counter
      component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
        component: frontend
    spec:
      containers:
      - name: httpd
        image: kamilbaran/nobleprog_training:httpd
        ports:
        - containerPort: 80
        env:
        - name: MONGO_CS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_CS

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongo-secret
data:
  MONGO_CS: bW9uZ29kYjovL2NvdW50ZXItbW9uZ286MjcwMTcK

---
apiVersion: v1
kind: Service
metadata:
  name: counter-httpd
  labels:
    app: counter
    component: frontend
spec:
  selector:
    app: counter
    component: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: counter
  labels:
    app: counter
spec:
  rules:
  - host: patryk.pg.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: counter-httpd
          servicePort: 80
