---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wget-cron-job
spec:
  schedule: "*/1 * * * *" # every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: alpine
            image: alpine
            command: ["wget", "training.default"]
          restartPolicy: Never
