apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-t28v1
  name: app-t28v1
  namespace: scheduling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-t28v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-t28v1
    spec:
      containers:
      - image: kamilbaran/training:app-v1
        name: training
        resources: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app-t28v1
              topologyKey: kubernetes.io/hostname
status: {}
