---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: networking
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: incoming-traffic
  namespace: networking
spec:
  podSelector:
    matchLabels:
      part-of: counter
  policyTypes:
  - Ingress
  ingress:
  - from: []
    ports: 
    - port: 80
  
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: outgoing-traffic
  namespace: networking
spec:
  podSelector:
    matchLabels:
      part-of: counter
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          name: mongo
    ports:
    - protocol: TCP
      port: 27017
  - to:
    - namespaceSelector: 
        matchLabels: 
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
