apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: t13-app
    version: v1
  name: t13-app
  namespace: upgrades
spec:
  replicas: 3
  selector:
    matchLabels:
      name: t13-app
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: t13-app
        version: v1
    spec:
      containers:
      - image: kamilbaran/training:training-app-v1
        imagePullPolicy: IfNotPresent
        name: training
        resources: {}
      restartPolicy: Always
