apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd-dc
  name: httpd-dc
  namespace: web-servers
spec:
  containers:
  - image: httpd:alpine
    name: httpd-dc
    securityContext:
      capabilities:
        drop: ["all"]
        add: ["cap_setuid", "cap_setgid", "cap_net_bind_service"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
