---
apiVersion: v1
data:
  index.html: <html><head><title>Task 7</title></head><body><p>This is the content
    for the Task 7.</p></body></html>
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-ex7-data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-t7v1
  name: nginx-t7v1
  namespace: web-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-t7v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-t7v1
    spec:
      containers:
      - image: nginx:1.18.0
        name: nginx
        resources: {}
        volumeMounts:
        - name: index-volume
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: index-volume
        configMap:
          name: nginx-ex7-data
          items:
          - key: index.html
            path: index.html
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-t7v1
  name: nginx-t7v1
spec:
  ports:
  - name: 80-80
    nodePort: 30087
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-t7v1
  type: NodePort
status:
  loadBalancer: {}
