apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-t26v1
  name: app-t26v1
  namespace: scheduling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-t26v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-t26v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - computing-node         
      containers:
      - image: kamilbaran/training:app-v1
        name: training
        resources: {}
status: {}
