apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-t2v1
  name: nginx-t2v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-t2v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-t2v1
    spec:
      containers:
      - image: nginx:alpine-stable
        name: nginx
        resources: {}
status: {}
