apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-t31v1
  name: app-t31v1
  namespace: resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-t31v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-t31v1
    spec:
      containers:
      - image: kamilbaran/training:app-v1
        name: training
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "100Mi"
            cpu: "200m"
status: {}
