apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httpd-cs
  name: httpd-cs
  namespace: web-servers
spec:
  containers:
  - image: httpd:alpine
    name: httpd-cs
    resources: {}
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - mountPath: /usr/local/apache2/logs/
        name: httpd
  volumes:
  - name: httpd
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
