---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-t2v1
  name: nginx-t2v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-t2v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-t2v1
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-t2v1
  name: nginx-t2v1
spec:
  ports:
  - name: 80-80
    nodePort: 30082
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-t2v1
  type: NodePort
status:
  loadBalancer: {}
