---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: t12-app
  name: t12-app
  namespace: upgrades
spec:
  replicas: 2
  selector:
    matchLabels:
      app: t12-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: t12-app
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: t12-app
  name: t12-app
  namespace: upgrades
spec:
  ports:
  - name: 80-80
    nodePort: 30912
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: t12-app
  type: NodePort
status:
  loadBalancer: {}
