apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tomcat-dc
  name: tomcat-dc
  namespace: web-servers
spec:
  containers:
  - image: tomcat:jdk11-openjdk-slim
    name: tomcat-dc
    securityContext:
      capabilities:
        drop: ["all"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
