---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
  namespace: counter
spec:
  ports:
  - port: 27017
    name: mongo
  clusterIP: None
  selector:
    app: mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
  namespace: counter
spec:
  selector:
    matchLabels:
      app: mongo # has to match .spec.template.metadata.labels
  serviceName: "mongo"
  replicas: 3 
  template:
    metadata:
      labels:
        app: mongo # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: kamilbaran/training:mongo
        ports:
        - containerPort: 27017
          name: mongo
        command: ["/usr/bin/mongod", "--bind_ip_all", "--replSet=test"]
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
              - /data/readiness.sh
          initialDelaySeconds: 5
          periodSeconds: 10
      dnsConfig:
        searches:
          - mongo.counter.svc.cluster.local
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mongo
            topologyKey: kubernetes.io/hostname
