apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-t25v1
  name: app-t25v1
  namespace: scheduling
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-t25v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-t25v1
    spec:
      containers:
      - image: kamilbaran/training:app-v1
        name: training
        resources: {}
      nodeSelector:
        type: computing-node
status: {}
