apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    app: counter
spec:
  selector:
    matchLabels:
      app: counter
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: httpd
        image: kamilbaran/nobleprog_training:httpd
        ports:
        - containerPort: 80
      - name: mongo
        image: kamilbaran/nobleprog_training:mongo
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: counter
  labels:
    app: counter
spec:
  type: NodePort
  selector:
    app: counter
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32081
