---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: training
  labels:
    app: training
    example: daemonset
spec:
  selector:
    matchLabels:
      app: training
      example: daemonset
  template:
    metadata:
      labels:
        app: training
        example: daemonset
    spec:
      containers:
      - name: training
        image: kamilbaran/nobleprog_training:training_app_v1
        imagePullPolicy: Always
      tolerations:
      - effect: NoSchedule
        operator: Exists

---
apiVersion: v1
kind: Service
metadata:
  name: training
  labels:
    app: training
    example: daemonset
spec:
  type: NodePort
  selector:
    app: training
    example: daemonset
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
