---
apiVersion: batch/v1
kind: Job
metadata:
  name: wget
spec:
  template:
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["wget", "training.default"]
      restartPolicy: Never
  backoffLimit: 6
  completions: 100
  parallelism: 2
  activeDeadlineSeconds: 300
  # ttlSecondsAfterFinished: 100
