apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  labels:
    app: training
spec:
  selector:
    matchLabels:
      app: training
  replicas: 3
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: kamilbaran/nobleprog_training:training_app_v1

---
apiVersion: v1
kind: Service
metadata:
  name: training
  labels:
    app: training
spec:
  selector:
    app: training
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

# Docs: https://kubernetes.io/docs/concepts/services-networking/ingress/
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: training
  labels:
    app: training
spec:
  rules:
  - http:
      paths:
      - path: /patryk
        pathType: Prefix
        backend:
          serviceName: training
          servicePort: 80
      # Below won't work unless Httpd virtual host configuration matches the path inside Ingress
      - path: /patryk_counter 
        backend:
          serviceName: counter
          servicePort: 80
          