apiVersion: apps/v1
kind: Deployment
metadata:
  name: training1
  labels:
    app: training2
spec:
  selector:
    matchLabels:
      app: training4
  replicas: 3
  template:
    metadata:
      labels:
        app: training4
    spec:
      containers:
      - name: training5
        image: kamilbaran/nobleprog_training:training_app_v1
---
apiVersion: v1
kind: Service
metadata:
  name: training6
  labels:
    app: training7
spec:
  type: ClusterIP
  selector:
    app: training4
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
