kind: Service
apiVersion: v1
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: wordpress-training
    app.kubernetes.io/version: "5.6"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: ""
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/instance: wordpress-training
    app.kubernetes.io/component: database
  ports:
  - port: 3306

