apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  labels:
    app: demo1
spec:
  selector:
    matchLabels:
      app: demo1
  replicas: 1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: httpd
        image: kamilbaran/nobleprog_training:httpd
        ports:
        - containerPort: 80
      - name: mongo
        image: kamilbaran/nobleprog_training:mongo
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: demo1
  labels:
    app: demo1
spec:
  selector:
    app: demo1
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
