---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-httpd
  labels:
    app: counter
    component: frontend
spec:
  selector:
    matchLabels:
      app: counter
      component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
        component: frontend
    spec:
      containers:
      - name: httpd
        image: kamilbaran/nobleprog_training:httpd
        ports:
        - containerPort: 80
        env:
        - name: MONGO_CS
          value: mongodb://counter-mongo:27017  

---
apiVersion: v1
kind: Service
metadata:
  name: counter-httpd
  labels:
    app: counter
    component: frontend
spec:
  selector:
    app: counter
    component: frontend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: counter
  labels:
    app: counter
spec:
  rules:
  - host: patryk.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: counter-httpd
          servicePort: 80
