---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-mongo
  labels:
    app: counter
    component: database
    version: 1.0.0
spec:
  selector:
    matchLabels:
      app: counter
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: mongo
        image: kamilbaran/nobleprog_training:mongo
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: counter-mongo
  labels:
    app: counter
    component: frontend
spec:
  selector:
    app: counter
    component: frontend
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017