---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-mongo
  labels:
    app: counter
    component: database
    version: 1.0.0
spec:
  selector:
    matchLabels:
      app: counter
      component: database
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
        component: database
    spec:
      containers:
      - name: mongo
        image: kamilbaran/nobleprog_training:mongo
        ports:
        - containerPort: 27017
        command: ["/usr/bin/mongod", "--dbpath=/data/db", "--bind_ip_all"] 


---
apiVersion: v1
kind: Service
metadata:
  name: counter-mongo
  labels:
    app: counter
    component: database
spec:
  selector:
    app: counter
    component: database
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017