---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-pods-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-pods-reader
  namespace: student
roleRef:
  kind: ClusterRole
  name: all-pods-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: student
  apiGroup: rbac.authorization.k8s.io
