---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patryk-all-pods-reader
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patryk-all-pods-reader
  namespace: patryk
roleRef:
  kind: ClusterRole
  name: patryk-all-pods-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: patryk
  apiGroup: rbac.authorization.k8s.io
