---
apiVersion: v1
kind: Namespace
metadata:
  name: patryk

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: deployment-manager
  namespace: patryk
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
- apiGroups: [""]
  resources: ["pods", "services", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: patryk-deployment-manager
  namespace: patryk
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""
subjects:
- kind: User
  name: patryk
  apiGroup: ""
