kind: Service
apiVersion: v1
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: wordpress-training
    app.kubernetes.io/version: "4.8"
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: ""
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: wordpress-training
    app.kubernetes.io/component: webserver
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080

