---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  labels:
    app: training
spec:
  selector:
    matchLabels:
      app: training
  replicas: 1
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: nginx
        image: nginx:1.19-alpine
        resources:
        volumeMounts:
        - name: html-data
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: content-maker
        image: alpine:latest
        command: ["/bin/sh", "-c", "echo My name is $POD_NAME and my IP is $POD_IP > /tmp/html/index.html"]
        volumeMounts:
        - name: html-data
          mountPath: /tmp/html
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
      - name: html-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: training
  labels:
    app: training
spec:
  type: NodePort
  selector:
    app: training
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32080
