---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  labels:
    app: training
spec:
  selector:
    matchLabels:
      app: training
  replicas: 1
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: nginx
        image: nginx:1.19-alpine
        resources:
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo You can use postStart and preStop hooks! > /usr/share/nginx/html/index.html"]
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
---
apiVersion: v1
kind: Service
metadata:
  name: training
  labels:
    app: training
spec:
  type: NodePort
  selector:
    app: training
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32080
