apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: rook-ceph-block
    # volume.beta.kubernetes.io/storage-class: default            #Azure
    # volume.beta.kubernetes.io/storage-class: managed-premium    #Azure
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: wordpress-training
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
