kind: Deployment
apiVersion: apps/v1
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: apache
    app.kubernetes.io/instance: wordpress-training
    app.kubernetes.io/version: "4.8"
    app.kubernetes.io/component: webserver
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: wordpress-training
      app.kubernetes.io/component: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: wordpress-training
        app.kubernetes.io/component: webserver
        app.kubernetes.io/part-of: wordpress
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-training-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        resources:
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
