---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-v1
  labels:
    app: training
    version: v1
spec:
  selector:
    matchLabels:
      app: training
      version: v1
  replicas: 2
  template:
    metadata:
      labels:
        app: training
        version: v1
    spec:
      containers:
      - name: training
        image: kamilbaran/nobleprog_training:training_app_v1
        resources:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - training
              - key: version
                operator: In
                values:
                - v1
            topologyKey: "kubernetes.io/hostname"
